language: cpp

matrix:
  include:
  - os: osx
    name: "Build"
    osx_image: xcode9.4
    compiler: clang

    script:
      - git clone https://github.com/acidanthera/audk -b master --depth=1 ../edk2
      - xcodebuild -configuration Debug -arch x86_64 -arch i386 ONLY_ACTIVE_ARCH=NO
      - xcodebuild -configuration Release -arch x86_64 -arch i386 ONLY_ACTIVE_ARCH=NO

    deploy:
      provider: releases
      skip_cleanup: true
      file: "build/*/*.zip"
      file_glob: true
      api_key:
        secure: kh3CAy7WchPAuzP8Ke6+6WyqC6XNsOv2j2bB+7TSmV3u3kugHhZ1X31RoP4zTXRwjoRQvPcCNRDDFBJxj787iVabZ1ewe9Zdy+gfelvtABViVa394L0NGKz5b9+1RQb2L8fBlvniri9ANe9ilHt8xm0YfSPbDw9k6i5q9WDjzoMjuNQ5Drlis/KknJ9ZksGZtbvnWiA8clmzEvhO/P9Er1v8+2qbLHMvYHbrfgNxfEiaHAz3jvJc6gBVRQJ7qCfITqnC9pdRodYeoR5kt1fctW22y9OsxVkBiwl6+RWO/SpXyd8EmzyALRJthlCtMIv+ycaFu4nOMFdYA/F+x05MkEI4UqBkvpKK5lRHUV3cX+XkQRTFFgbcKx/TQEQLqYgiIddvovLhDEIwRWevDiC+VlekZiUAR4bG9cIhizU3ebjFJqsDCGDzkH0hfQ+J05O2V70v555i8dOeRtOazvzPZ3njNuM+s0l/3/Wb9ejxsWeDnjjEDeF1vodv61xHJBEltRI5WL3lDpJvdVCbo1gcv3mJ73vlmQM/ixsdJUfqYQO9ibK7+V3rLZANtx+QoiPrims5/NGpQeQjK7hSqk0c2mX7n+f899DQepQwATSxvgcSXhPYsSsW6rWodvt2OrxpEvN7BfkgavVQA01jQjQz8+wVVXal7ByEGHRfk9RfKFE=
      on:
        tags: true

  - os: osx
    name: "Analyze Clang"
    osx_image: xcode9.4
    compiler: clang

    script:
      - git clone https://github.com/acidanthera/audk -b master --depth=1 ../edk2
      - xcodebuild analyze -quiet -scheme gfxutil -configuration Debug CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]
      - xcodebuild analyze -quiet -scheme gfxutil -configuration Release CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]
